#!/usr/bin/env python

# Copyright 2014 Massachusetts Open Cloud Contributors
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the
# License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an "AS
# IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either
# express or implied. See the License for the specific language
# governing permissions and limitations under the License.

"""This is a simple script that can be used to power cycle all nodes registered in the HaaS."""

from haas import api

if len(sys.argv) < 2:
    print('Usage:  power_cycle_nodes <project>')
else:
    project = sys.argv[1]
    nodes = json.loads(api.list_free_nodes(project))
    for node in nodes:
        api.node_power_cycle(node)
